library(DESeq2)
CountMatrix1<-read.csv("F://data//Glauconem_trihymena_LHA20170827//RNA//S_C.csv",sep=",",row.names="gene_id")
names(CountMatrix1)<-c("RS1","RS2","RS3","RC1","RC2","RC3")
ColumnData<- data.frame(row.names=colnames(CountMatrix1),samName=colnames(CountMatrix1), condition=rep(c("S","C"),each=3))
dds<-DESeqDataSetFromMatrix(countData = CountMatrix1, colData = ColumnData, design = ~ condition)
dds<-DESeq(dds) 
res<-results(dds)
summary(res)
head(res)
table(res$padj <0.05)
res<- res[order(res$padj),]
resdata <- merge(as.data.frame(res), as.data.frame(counts(dds, normalized=TRUE)),by="row.names",sort=FALSE)
write.csv(resdata,file = "F://data//Glauconem_trihymena_LHA20170827//RNA//S_C_normalized.csv")
deg <- subset(res, padj <= 0.05 & abs(log2FoldChange) >= 1)
summary(deg)
write.csv(deg, "F://data//Glauconem_trihymena_LHA20170827//RNA//S_C_deg.csv")